name: dolla-consensus-proposing-receptioning
version: 0.0.0.1
extra-source-files:
  - README.md

ghc-options:
  - -Wall
##  - -j
library:
  source-dirs: lib

  dependencies:
    - dolla-base == 1.0.0
    - dolla-consensus-base == 1.0.0
    - dolla-consensus-proposing-receptioning-settings

    - base == 4.13.0.0
    - mtl == 2.2.2
    - servant-server == 0.16.2
    - servant-client == 0.16.0.1
    - http-client == 0.6.4.1
    - warp == 3.3.12
    - validation == 1.1
    - aeson == 1.4.7.1

executables:
  dolla-consensus-proposing-receptioning :
    main: Executables.hs
    source-dirs: app
    ghc-options:
      - -main-is Executables.receptioning
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - dolla-consensus-proposing-receptioning
      - base == 4.13.0.0

tests:
  dolla-consensus-proposing-receptioning-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - dolla-consensus-proposing-receptioning
      - dolla-base
      - base
      - streamly == 0.7.2
      - mtl == 2.2.2
      - random == 1.1
      - hspec
      - QuickCheck
      - generic-arbitrary
      - quickcheck-instances
      - interpolatedstring-perl6 == 1.0.2
      - aeson == 1.4.7.1
      - uuid == 1.3.13
      - dolla-consensus-base == 1.0.0