name: dolla-consensus-proposing-simulating
version: 0.0.0.1
extra-source-files:
  - README.md

ghc-options:
  - -Wall

dependencies:
  - dolla-base == 1.0.0
  - base == 4.13.0.0
  - dolla-consensus-proposing-simulating-settings
  - dolla-consensus-proposing-receptioning-settings

library:
  source-dirs: library

  dependencies:
    - dolla-consensus-base == 1.0.0
    - dolla-consensus-proposing-receptioning
    - dolla-consensus-proposing-staging
    - mtl == 2.2.2
    - text == 1.2.4.0
    - byline == 0.3.2.1
    - random == 1.1
    - uuid == 1.3.13
    - aeson == 1.4.7.1
    - streamly == 0.7.2
    - exceptions == 0.10.4
    - bytestring == 0.10.10.0

executables:
  dolla-consensus-proposing-simulating :
    main: Executables.hs
    source-dirs: executables
    ghc-options:
      - -main-is Executables.simulating
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - dolla-consensus-proposing-simulating




