name: dolla-consensus-proposer-client-simulator
version: 0.0.0.1
extra-source-files:
  - README.md

ghc-options:
  - -Wall
  - -j

dependencies:
  - dolla-base == 1.0.0
  - base == 4.13.0.0
  - dolla-consensus-proposer-client-simulator-settings
  - dolla-consensus-proposer-receptionist-settings

library:
  source-dirs: lib

  dependencies:
    - dolla-consensus-base == 1.0.0
    - dolla-consensus-proposer-receptionist

    - mtl == 2.2.2
    - text == 1.2.4.0
    - byline == 0.3.2.1
    - random == 1.1
    - uuid == 1.3.13
    - aeson == 1.4.7.1
    - streamly == 0.7.2

executables:
  dolla-consensus-proposer-client-simulator :
    main: Executables.hs
    source-dirs: app
    ghc-options:
      - -main-is Executables.clientSimulator
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - dolla-consensus-proposer-client-simulator




