name: dolla-consensus-proposing-detecting-tension-settings

ghc-options:
  - -Wall

library:
  source-dirs: library

  dependencies:
    - dolla-base == 1.0.0
    - base == 4.13.0.0
    - aeson == 1.4.7.1


