name: dolla-consensus-proposing-zeus
version: 0.0.0.1
extra-source-files:
  - README.md

ghc-options:
  - -Wall
  - -j

library:
  source-dirs: lib

  dependencies:

    - dolla-base == 1.0.0
    - dolla-consensus-base == 1.0.0

    - dolla-consensus-proposing-simulating-settings
    - dolla-consensus-proposing-receptioning-settings
    - dolla-consensus-proposing-packaging-settings
    - dolla-consensus-proposing-detecting-starvation-settings

    - base == 4.13.0.0
    - text == 1.2.4.0
    - mtl == 2.2.2
    - streamly == 0.7.2
    - interpolatedstring-perl6 == 1.0.2
    - adjunctions == 4.4
    - unordered-containers == 0.2.10.0
    - hashable
    - pipes
    - http-client == 0.6.4.1
    - uuid == 1.3.13
    - either == 5.0.1
    - timers == 0.2.0.3
    - suspend == 0.2.0.0
    - random == 1.1
    - validation == 1.1
    - async
    - aeson
    - streaming
    - bytestring == 0.10.10.0
    - lens
    - directory == 1.3.6.0
    - safe == 0.3.19
    - transformers == 0.5.6.2
    - mmorph == 1.1.3
    - ilist ==0.4.0.1
    - concurrent-extra == 0.7.0.12
    - exceptions == 0.10.4
    - turtle == 1.5.19
    - byline == 0.3.2.1

executables:
  dolla-consensus-proposing-zeus :
    main: Executables.hs
    source-dirs: app
    ghc-options:
      - -main-is Executables.executeZeus
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - dolla-consensus-proposing-zeus
      - base == 4.13.0.0

